/*
 * OnfonMediaSMSGateway.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using OnfonMediaSMSGateway.Standard.Controllers;
using OnfonMediaSMSGateway.Standard.Http.Client;
using OnfonMediaSMSGateway.Standard.Utilities;

namespace OnfonMediaSMSGateway.Standard
{
    public partial class OnfonMediaSMSGatewayClient
    {

        /// <summary>
        /// Singleton access to Account controller
        /// </summary>
        public AccountController Account
        {
            get
            {
                return AccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Template controller
        /// </summary>
        public TemplateController Template
        {
            get
            {
                return TemplateController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SMS controller
        /// </summary>
        public SMSController SMS
        {
            get
            {
                return SMSController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to GROUP controller
        /// </summary>
        public GROUPController GROUP
        {
            get
            {
                return GROUPController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Campaign controller
        /// </summary>
        public CampaignController Campaign
        {
            get
            {
                return CampaignController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public OnfonMediaSMSGatewayClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public OnfonMediaSMSGatewayClient(string accessKey = "ACCESS_KEY", string apiKey = "API_KEY", string clientId = "CLIENT_ID")
        {
            Configuration.AccessKey = accessKey;
            Configuration.ApiKey = apiKey;
            Configuration.ClientId = clientId;
        }
        #endregion
    }
}